# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desk_hassou_03' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desk_hassou_03
  pod 'Realm' , '~> 3.19.0'
  pod 'RealmSwift' , '~> 3.19.0'
end
